### ISSUE TITLE
people mad at me for last active times

### ISSUE THREAD

**Issue by kbala444** [samm81/pesterbot#9]
hello sam

sumanth and i have discussed that pesterbot forces you to reveal yourself as active on facebook
as a result, it is much harder to ignore people who might be checking your last active times
please rectify this issue by either submitting a pull request to facebook or using an alternate channel of communication

thanks,
karthik

**Comment by samm81** [comment]
well it only marks you as active if you respond, which you never do so

**Comment by kbala444** [comment]
or maybe i dont respond because of my last active time

**Comment by samm81** [comment]
or maybe you shouldn't be ignoring your girlfriend

**Comment by kbala444** [comment]
won't stand for this libel
